apiVersion: v1
kind: Service
metadata:
  name: frontend-services
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   selector:
#     app: backend
#   ports:
#   - protocol: TCP
#     port: 3898
#     targetPort: 3898
